Filtermovie
WildCodeSchool/2023-02-JS-Reims-project-2-cine-genius pull request #7
Opened 2023-04-26 14:44 UTC by khaliev

Filtering with the options retrieved from the Quiz component

2023-04-26 14:47 UTC, khaliev commented
Filtering with the options retrieved from the Quiz component

2023-04-27 12:09 UTC, rocambille requested changes

2023-04-27 12:09 UTC, rocambille commented on package.json
> +    "react-router": "^6.10.0"
uninstall react router from root

2023-04-27 12:36 UTC, khaliev commented on package.json
> +    "react-router": "^6.10.0"
> uninstall react router from root
react router uninstalled ✅

2023-04-27 15:01 UTC, merged